- name: Add AWX requirements
  hosts: training-awx
  any_errors_fatal: true
  become: yes

  roles: 
    - { role: davidkarban.repo_epel, tags: epel }
    - { role: VerosK.docker, tags: docker }
#    - { role: VerosK.nginx, tags: nginx }

  tasks:
    - name: Ensure firewall allow access to awx machine
      firewalld:
        immediate: true
        permanent: true
        port: 80/tcp
        state: enabled
      when: with_firewalld
      ignore_errors: yes

    - name: Stop nginx and httpd (when present)
      service:
        name: '{{ item }}'
        state: stopped
      loop: [ httpd, nginx ]
      ignore_errors: yes

- name: Add AWX
  hosts: training-awx
  any_errors_fatal: true
  become: yes

  roles:
    - role: awx
      tags: awx
