- name: Add AWX requirements
  hosts: training-awx
  any_errors_fatal: true
  become: yes

  roles: 
    - role: davidkarban.repo_epel
      tags: epel
    - role: VerosK.docker
      tags: docker

  tasks:
    - name: Ensure firewall allow access to awx machine
      firewalld:
        immediate: true
        permanent: true
        port: 80/tcp
        state: enabled
      when: with_firewalld
      ignore_errors: yes

    - name: Stop httpd
      service:
        name: 'httpd'
        state: stopped
      ignore_errors: yes

- name: Add AWX
  hosts: training-awx
  any_errors_fatal: true
  become: yes

  roles:
    - role: awx
      tags: awx

- name: Add nginx when required
  hosts: training-awx
  any_errors_fatal: true
  become: yes

  roles:
    - role: VerosK.nginx
      tags: nginx
      when: with_nginx|default(True)

