

nginx_sites: '{{ nginx_sites_ssl }}'
nginx_firewalld_ignore_errors: true

_nginx_security_headers: |
    add_header Strict-Transport-Security max-age=15768000;
    add_header X-XSS-Protection "1; mode=block";

    add_header Referrer-Policy "no-referrer, strict-origin-when-cross-origin";
    add_header X-Content-Type-Options  "nosniff";
    add_header Content-Security-Policy $content_security_policy;
    add_header X-Frame-Options $x_frame_options;

nginx_sites_ssl:
  - name: '{{ ansible_fqdn }}'
    is_default: true
    with_ssl: true
    request_acme_cert: true
    root_config: |

      location / {
            proxy_pass http://127.0.0.1:8052/;
            proxy_read_timeout 90;
            proxy_set_header Host        $http_host;
            proxy_set_header X-Forwarded-Proto "https";
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-User $remote_user;
            proxy_set_header X-Request-ID $request_id;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            #  security headers
            {{ _nginx_security_headers }}
      }

nginx_sites_nossl:
  - name: '{{ ansible_fqdn }}'
    is_default: true
    with_ssl: false
    request_acme_cert: false
    root_config: |

      location / {
            proxy_pass http://127.0.0.1:8052/;
            proxy_read_timeout 90;
            proxy_set_header Host        $http_host;
            proxy_set_header X-Forwarded-Proto "http";
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-User $remote_user;
            proxy_set_header X-Request-ID $request_id;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

      }
